<?xml version="1.0" encoding="UTF-8"?><testrun name="TestCalc" project="Calc" tests="6" started="6" failures="1" errors="0" ignored="0">
  <testsuite name="com.indus.training.core.TestCalc" time="0.023">
    <testcase name="testAdditionSenario1" classname="com.indus.training.core.TestCalc" time="0.015"/>
    <testcase name="testAdditionSenario2" classname="com.indus.training.core.TestCalc" time="0.0"/>
    <testcase name="testAdditionSenario3" classname="com.indus.training.core.TestCalc" time="0.0"/>
    <testcase name="testDivision" classname="com.indus.training.core.TestCalc" time="0.007">
      <failure>junit.framework.AssertionFailedError: expected:&lt;10.0&gt; but was:&lt;5.0&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:120)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:129)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:288)&#13;
	at com.indus.training.core.TestCalc.testDivision(TestCalc.java:108)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:124)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testMultiply" classname="com.indus.training.core.TestCalc" time="0.001"/>
    <testcase name="testSubtrat" classname="com.indus.training.core.TestCalc" time="0.0"/>
  </testsuite>
</testrun>
